// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_cor_cpp
NumericMatrix fast_cor_cpp(NumericMatrix mat, std::string method);
RcppExport SEXP _BioTransition_fast_cor_cpp(SEXP matSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_cor_cpp(mat, method));
    return rcpp_result_gen;
END_RCPP
}
// fast_module_score_cpp
List fast_module_score_cpp(NumericMatrix cor_matrix, NumericVector variation, IntegerVector module_genes, int all_genes, bool add_size);
RcppExport SEXP _BioTransition_fast_module_score_cpp(SEXP cor_matrixSEXP, SEXP variationSEXP, SEXP module_genesSEXP, SEXP all_genesSEXP, SEXP add_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cor_matrix(cor_matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type variation(variationSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type module_genes(module_genesSEXP);
    Rcpp::traits::input_parameter< int >::type all_genes(all_genesSEXP);
    Rcpp::traits::input_parameter< bool >::type add_size(add_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_module_score_cpp(cor_matrix, variation, module_genes, all_genes, add_size));
    return rcpp_result_gen;
END_RCPP
}
// fast_cor_pval_cpp
List fast_cor_pval_cpp(NumericMatrix mat, std::string method);
RcppExport SEXP _BioTransition_fast_cor_pval_cpp(SEXP matSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_cor_pval_cpp(mat, method));
    return rcpp_result_gen;
END_RCPP
}
// fast_sspn_batch
List fast_sspn_batch(NumericMatrix expr_mat, IntegerVector ref_indices, IntegerVector case_indices, CharacterVector ppi_gene1, CharacterVector ppi_gene2, CharacterVector gene_names);
RcppExport SEXP _BioTransition_fast_sspn_batch(SEXP expr_matSEXP, SEXP ref_indicesSEXP, SEXP case_indicesSEXP, SEXP ppi_gene1SEXP, SEXP ppi_gene2SEXP, SEXP gene_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr_mat(expr_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ref_indices(ref_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type case_indices(case_indicesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ppi_gene1(ppi_gene1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ppi_gene2(ppi_gene2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type gene_names(gene_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_sspn_batch(expr_mat, ref_indices, case_indices, ppi_gene1, ppi_gene2, gene_names));
    return rcpp_result_gen;
END_RCPP
}
// fast_bh_adjust
NumericVector fast_bh_adjust(NumericVector p_values);
RcppExport SEXP _BioTransition_fast_bh_adjust(SEXP p_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p_values(p_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_bh_adjust(p_values));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BioTransition_fast_cor_cpp", (DL_FUNC) &_BioTransition_fast_cor_cpp, 2},
    {"_BioTransition_fast_module_score_cpp", (DL_FUNC) &_BioTransition_fast_module_score_cpp, 5},
    {"_BioTransition_fast_cor_pval_cpp", (DL_FUNC) &_BioTransition_fast_cor_pval_cpp, 2},
    {"_BioTransition_fast_sspn_batch", (DL_FUNC) &_BioTransition_fast_sspn_batch, 6},
    {"_BioTransition_fast_bh_adjust", (DL_FUNC) &_BioTransition_fast_bh_adjust, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BioTransition(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
