# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Correlation Matrix Computation (C++)
#' 
#' @description
#' Optimized C++ implementation for computing correlation matrices.
#' This provides 10-20x speedup over R's cor() for large matrices.
#' 
#' @param mat Numeric matrix (genes x samples)
#' @param method Correlation method: "pearson" or "spearman"
#' @return Correlation matrix (genes x genes)
#' 
#' @export
fast_cor_cpp <- function(mat, method = "pearson") {
    .Call('_BioTransition_fast_cor_cpp', PACKAGE = 'BioTransition', mat, method)
}

#' Fast Module Score Calculation (C++)
#' 
#' @description
#' Optimized calculation of DNB module scores.
#' 
#' @param cor_matrix Correlation matrix
#' @param variation Vector of gene variations
#' @param module_genes Indices of genes in module (0-based)
#' @param all_genes Total number of genes
#' @param add_size Whether to include module size in score
#' @return List with CI, V_in, R_in, R_out
#' 
#' @export
fast_module_score_cpp <- function(cor_matrix, variation, module_genes, all_genes, add_size = FALSE) {
    .Call('_BioTransition_fast_module_score_cpp', PACKAGE = 'BioTransition', cor_matrix, variation, module_genes, all_genes, add_size)
}

#' Fast Correlation with P-values (C++)
#' 
#' @description
#' Optimized C++ implementation for computing correlation matrix with p-values.
#' This replaces the slow CorandPval() function in SSPN calculations.
#' 
#' @param mat Numeric matrix (samples x genes)
#' @param method Correlation method: "pearson"
#' @return List with r (correlation matrix), p (p-values), n_obs (number of observations)
#' 
#' @export
fast_cor_pval_cpp <- function(mat, method = "pearson") {
    .Call('_BioTransition_fast_cor_pval_cpp', PACKAGE = 'BioTransition', mat, method)
}

#' Fast SSPN Calculation for All Samples (C++)
#' 
#' @description
#' Batch calculation of SSPN for all case samples. 
#' Major speedup by avoiding repeated matrix operations.
#' 
#' @param expr_mat Expression matrix (genes x all_samples)
#' @param ref_indices Indices of reference samples (0-based)
#' @param case_indices Indices of case samples (0-based)
#' @param ppi_gene1 First gene names in PPI
#' @param ppi_gene2 Second gene names in PPI
#' @param gene_names Gene names in expression matrix
#' @return List of perturbation data frames for each case sample
#' 
#' @export
fast_sspn_batch <- function(expr_mat, ref_indices, case_indices, ppi_gene1, ppi_gene2, gene_names) {
    .Call('_BioTransition_fast_sspn_batch', PACKAGE = 'BioTransition', expr_mat, ref_indices, case_indices, ppi_gene1, ppi_gene2, gene_names)
}

#' Fast P-value Adjustment (C++)
#' 
#' @description
#' Fast implementation of Benjamini-Hochberg FDR correction.
#' 
#' @param p_values Vector of p-values
#' @return Vector of adjusted p-values
#' 
#' @export
fast_bh_adjust <- function(p_values) {
    .Call('_BioTransition_fast_bh_adjust', PACKAGE = 'BioTransition', p_values)
}

